### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by tajmone** [ksherlock/sublime-lemon#1]
Nice package!

Could you please add a license file, so I can edit its contents and contribute to the project?

Without a license, package usage is restricted to cloning and forking it as-is.

Thanks.

**Comment by ksherlock** [comment]
CC0 1.0 Universal license has been added.

**Comment by tajmone** [comment]
Thanks! I've updated the info in my project that mentions Sublime-Lemon:

- https://github.com/tajmone/lemon-grove#sublime-text
